### ISSUE TITLE
Failed to Start Bot at the first time installation

### ISSUE THREAD

**Issue by b3nydishub** [CHR-onicles/Whatsapp-bot#131]
i got this errror at the first time instalation 

=========================================
npm start
> whatsapp-bot@0.1.0 start E:\bot3
> node main.js

[DB] Successful connection to DB
[PREFIX] Current prefix: "undefined"
[SERVER] Server is running on port 3000
(node:9924) UnhandledPromiseRejectionWarning: MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (E:\bot3\node_modules\mongoose\lib\connection.js:694:11)
    at E:\bot3\node_modules\mongoose\lib\index.js:380:10
    at E:\bot3\node_modules\mongoose\lib\helpers\promiseOrCallback.js:41:5
    at new Promise (<anonymous>)
    at promiseOrCallback (E:\bot3\node_modules\mongoose\lib\helpers\promiseOrCallback.js:40:10)
    at Mongoose._promiseOrCallback (E:\bot3\node_modules\mongoose\lib\index.js:1233:10)
    at Mongoose.connect (E:\bot3\node_modules\mongoose\lib\index.js:379:20)
    at Object.<anonymous> (E:\bot3\main.js:36:10)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:9924) UnhandledPromiseRejectionWarning: MongooseError: Operation `miscellaneous-devs.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (E:\bot3\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:153:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:9924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:9924) UnhandledPromiseRejectionWarning: MongooseError: Operation `files-devs.countDocuments()` buffering timed out after 10000ms
    at Timeout.<anonymous> (E:\bot3\node_modules\mongoose\lib\drivers\node-mongodb-native\collection.js:153:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:9924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
=========================================

is there any solution or instalation guide?

**Comment by CHR-onicles** [comment]
Hi @b3nydishub,

Do you have a `.env` file with the required env variables `DEV_PREFIX` and `MONGO_URL`?
It seems from the error log that they are undefined because you may not have invoked them properly.
I have an [examples directory](https://github.com/CHR-onicles/Whatsapp-bot/tree/main/examples) which has a sample `.env` file in case you missed it.

Currently there is no installation guide, so I'll work on that soon.

**Comment by b3nydishub** [comment]
thank you very much
